language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
install: 
  - pip install -e .
  - pip install -r dev-requirements.txt
script:
  - PYTHONPATH='.:tests' py.test
